global:
  scrape_interval: 15s  # Intervalo padrão de coleta de métricas para todos os jobs

scrape_configs:
  - job_name: 'prometheus'  # Nome do job para o Prometheus
    static_configs:
      - targets: ['localhost:9090']  # Definição do alvo, neste caso o próprio Prometheus
 
  - job_name: 'flask_app'
    static_configs:
      - targets: ['flask:5000']   
